import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import  Header  from '../../Components/Header/Header'
import Footer from "../../Components/Footer/Footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div>

      <Header />
        <div className={inter.className}>{children}</div>
      <Footer />
      </div>
    </html>
  )
}
